; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Stock Scanner"
#define MyAppVersion "1.0.19"
#define MyAppPublisher "PrinceBot.Co.,Ltd"
#define MyAppExeName "stock_scanner_mobile.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{238618C9-FEE8-4F86-9DE2-47A3AA71BA65}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UsePreviousAppDir=yes
CloseApplications=force
RestartApplications=yes
DirExistsWarning=no
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\my-api
OutputBaseFilename=StockScannerSetup-v1.0.19
SetupIconFile=C:\my-api\mobile_app\windows\runner\resources\app_icon.ico
SolidCompression=yes
WizardStyle=classic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "thai"; MessagesFile: "compiler:Languages\Thai.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\my-api\mobile_app\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\my-api\Start_Web_App.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\my-api\launch_web_silent.vbs"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\my-api\Start_Desktop_App.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\my-api\launch_desktop_silent.vbs"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{sys}\wscript.exe"; Parameters: """{app}\launch_desktop_silent.vbs"""; IconFilename: "{app}\{#MyAppExeName}"
Name: "{autoprograms}\Stock Scanner Web"; Filename: "{sys}\wscript.exe"; Parameters: """{app}\launch_web_silent.vbs"""; IconFilename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{sys}\wscript.exe"; Parameters: """{app}\launch_desktop_silent.vbs"""; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{autodesktop}\Stock Scanner Web"; Filename: "{sys}\wscript.exe"; Parameters: """{app}\launch_web_silent.vbs"""; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{sys}\wscript.exe"; Parameters: """{app}\launch_desktop_silent.vbs"""; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

