import "dart:async" show unawaited;
import "package:flutter/foundation.dart" show defaultTargetPlatform, kIsWeb;
import "package:flutter/material.dart";
import "package:flutter/services.dart" show HapticFeedback, MethodChannel, SystemSound, SystemSoundType;
import "package:mobile_scanner/mobile_scanner.dart";

import "api_service.dart";
import "models.dart";
import "theme/app_theme.dart";

class ScanPage extends StatefulWidget {
  const ScanPage({
    super.key,
    required this.api,
    required this.currentUser,
    required this.onOpenProductDetails,
  });

  final StockApiService api;
  final AppUser currentUser;
  final void Function(BuildContext context, Product product) onOpenProductDetails;

  @override
  State<ScanPage> createState() => _ScanPageState();
}

class _ScanPageState extends State<ScanPage> {
  static const MethodChannel _scanSoundChannel =
      MethodChannel("stock_scanner/sound");
  final TextEditingController _barcodeController = TextEditingController();
  final TextEditingController _qtyController = TextEditingController(text: "1");
  final TextEditingController _noteController = TextEditingController();
  final TextEditingController _referenceController = TextEditingController();
  final TextEditingController _productNameController = TextEditingController();
  final TextEditingController _productSkuController = TextEditingController();
  final TextEditingController _productUnitController =
      TextEditingController(text: "pcs");
  final TextEditingController _productCategoryController =
      TextEditingController();
  final TextEditingController _productLocationController =
      TextEditingController();

  String _action = "in";
  bool _newProductMode = false;
  bool _isSubmitting = false;
  bool _isGeneratingBarcode = false;
  bool _scannerEnabled = true;
  bool _isSkuManuallyEdited = false;
  ScanResult? _lastResult;
  String? _lastAutoGeneratedSku;

  @override
  void dispose() {
    _barcodeController.dispose();
    _qtyController.dispose();
    _noteController.dispose();
    _referenceController.dispose();
    _productNameController.dispose();
    _productSkuController.dispose();
    _productUnitController.dispose();
    _productCategoryController.dispose();
    _productLocationController.dispose();
    super.dispose();
  }

  void _showSnack(String message) {
    showAppSnack(context, message);
  }

  Future<void> _playNativeScanBeep() async {
    try {
      await _scanSoundChannel.invokeMethod<void>("playScanBeep");
    } catch (_) {
      await SystemSound.play(SystemSoundType.click);
    }
  }

  Future<void> _playScanHaptic() async {
    try {
      await HapticFeedback.lightImpact();
    } catch (_) {
      await HapticFeedback.selectionClick();
    }
  }

  void _playScanFeedback() {
    final settings = AppSettingsScope.of(context);
    if (settings.enableHaptic) {
      unawaited(_playScanHaptic());
    }
    if (!settings.enableSound) {
      return;
    }
    if (kIsWeb) {
      unawaited(SystemSound.play(SystemSoundType.click));
      return;
    }
    if (defaultTargetPlatform == TargetPlatform.android) {
      unawaited(_playNativeScanBeep());
      return;
    }
    unawaited(SystemSound.play(SystemSoundType.click));
  }

  String _trimSkuSegment(String value, int maxLength) {
    final cleaned = value.replaceAll(RegExp(r"[^A-Z0-9]"), "");
    if (cleaned.isEmpty) {
      return "";
    }
    return cleaned.length <= maxLength
        ? cleaned
        : cleaned.substring(0, maxLength);
  }

  String _buildAutoSku() {
    final normalizedName = _productNameController.text.trim().toUpperCase();
    final words = normalizedName
        .split(RegExp(r"[^A-Z0-9]+"))
        .where((item) => item.isNotEmpty)
        .toList();

    String namePart;
    if (words.isEmpty) {
      namePart = "ITEM";
    } else if (words.length == 1) {
      namePart = _trimSkuSegment(words.first, 6);
    } else {
      final first = _trimSkuSegment(words[0], 3);
      final second = _trimSkuSegment(words[1], 3);
      namePart = [first, second].where((item) => item.isNotEmpty).join("-");
    }

    if (namePart.isEmpty) {
      namePart = "ITEM";
    }

    final barcodePart = _trimSkuSegment(
      _barcodeController.text.trim().toUpperCase(),
      24,
    );
    final tail = barcodePart.isEmpty
        ? "AUTO"
        : (barcodePart.length <= 4
            ? barcodePart
            : barcodePart.substring(barcodePart.length - 4));

    return "$namePart-$tail";
  }

  void _syncAutoSku({bool force = false}) {
    if (!_newProductMode) {
      return;
    }

    final nextSku = _buildAutoSku();
    final currentSku = _productSkuController.text.trim();
    final shouldReplace = force ||
        currentSku.isEmpty ||
        (!_isSkuManuallyEdited &&
            currentSku == (_lastAutoGeneratedSku ?? currentSku));

    if (!shouldReplace) {
      return;
    }

    _productSkuController.text = nextSku;
    _productSkuController.selection =
        TextSelection.collapsed(offset: nextSku.length);
    _lastAutoGeneratedSku = nextSku;
    _isSkuManuallyEdited = false;
  }

  InputDecoration _scanInputDecoration(
    String label, {
    String? hintText,
    Widget? suffixIcon,
  }) {
    return InputDecoration(
      labelText: label,
      hintText: hintText,
      suffixIcon: suffixIcon,
      filled: true,
      fillColor: Colors.white.withOpacity(0.96),
      labelStyle: TextStyle(
        color: brandInk.withOpacity(0.88),
        fontWeight: FontWeight.w700,
        fontSize: 14,
      ),
      floatingLabelStyle: const TextStyle(
        color: brandDeep,
        fontWeight: FontWeight.w800,
      ),
      hintStyle: TextStyle(
        color: brandInk.withOpacity(0.52),
        fontWeight: FontWeight.w500,
      ),
      contentPadding: const EdgeInsets.symmetric(
        horizontal: spaceMd,
        vertical: 18,
      ),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(radiusMd),
        borderSide: BorderSide(color: brandPrimary.withOpacity(0.16)),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(radiusMd),
        borderSide: BorderSide(color: brandPrimary.withOpacity(0.16)),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(radiusMd),
        borderSide: const BorderSide(color: brandPrimary, width: 1.5),
      ),
    );
  }

  Future<void> _generateBarcode({bool silent = false}) async {
    try {
      setState(() {
        _isGeneratingBarcode = true;
      });
      final barcode = await widget.api.getNextBarcode();
      if (!mounted) {
        return;
      }
      setState(() {
        _barcodeController.text = barcode;
      });
      _syncAutoSku();
      if (!silent) {
        _showSnack("สร้าง barcode ใหม่แล้ว");
      }
    } catch (error) {
      if (!silent) {
        _showSnack(error.toString().replaceFirst("Exception: ", ""));
      }
    } finally {
      if (mounted) {
        setState(() {
          _isGeneratingBarcode = false;
        });
      }
    }
  }

  Future<void> _submit() async {
    final quantity = int.tryParse(_qtyController.text.trim());
    final shouldCreateProduct = _newProductMode;

    if (shouldCreateProduct && _productSkuController.text.trim().isEmpty) {
      _syncAutoSku(force: true);
    }

    if (_barcodeController.text.trim().isEmpty ||
        quantity == null ||
        quantity <= 0) {
      _showSnack("กรุณากรอก barcode และจำนวนให้ครบ");
      return;
    }
    if (shouldCreateProduct && _productNameController.text.trim().isEmpty) {
      _showSnack("กรุณากรอกชื่อสินค้าเมื่อเปิดโหมดสินค้าใหม่");
      return;
    }

    setState(() {
      _isSubmitting = true;
    });

    try {
      final result = await widget.api.submitScan(
        barcode: _barcodeController.text.trim(),
        action: shouldCreateProduct ? "in" : _action,
        quantity: quantity,
        actorId: widget.currentUser.userId,
        actorName: widget.currentUser.userName,
        note: _noteController.text.trim().isEmpty
            ? null
            : _noteController.text.trim(),
        reference: _referenceController.text.trim().isEmpty
            ? null
            : _referenceController.text.trim(),
        autoCreateProduct: shouldCreateProduct,
        productName: _productNameController.text.trim().isEmpty
            ? null
            : _productNameController.text.trim(),
        productUnit: _productUnitController.text.trim().isEmpty
            ? "pcs"
            : _productUnitController.text.trim(),
        productCategory: _productCategoryController.text.trim().isEmpty
            ? null
            : _productCategoryController.text.trim(),
        productLocation: _productLocationController.text.trim().isEmpty
            ? null
            : _productLocationController.text.trim(),
        productSku: _productSkuController.text.trim().isEmpty
            ? null
            : _productSkuController.text.trim(),
      );
      setState(() {
        _lastResult = result;
      });
      if (result.productCreated) {
        _showSnack("สร้างสินค้าใหม่และบันทึกรายการเรียบร้อย");
      } else if (result.lowStock) {
        _showSnack("บันทึกแล้ว และสินค้านี้อยู่ในระดับเตือน");
      } else {
        _showSnack("บันทึกรายการเรียบร้อย");
      }
    } catch (error) {
      _showSnack(error.toString().replaceFirst("Exception: ", ""));
    } finally {
      if (mounted) {
        setState(() {
          _isSubmitting = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: Color.lerp(brandSurface, Colors.white, 0.14)!,
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          const _PageHeader(
            title: "สแกนและบันทึก",
            subtitle: "คุณใช้ได้ทั้งโหมดสแกนปกติและโหมดสินค้าใหม่",
          ),
          const SizedBox(height: 16),
          SegmentedButton<bool>(
            segments: const [
              ButtonSegment(
                  value: false,
                  label: Text("สแกนเข้า/ออก"),
                  icon: Icon(Icons.qr_code_scanner)),
              ButtonSegment(
                  value: true,
                  label: Text("สินค้าใหม่"),
                  icon: Icon(Icons.add_box_outlined)),
            ],
            selected: {_newProductMode},
            onSelectionChanged: (selection) {
              final wantsNewMode = selection.first;
              setState(() {
                _newProductMode = wantsNewMode;
              });
              if (wantsNewMode && _barcodeController.text.trim().isEmpty) {
                _generateBarcode(silent: true);
              } else if (wantsNewMode) {
                _syncAutoSku();
              }
            },
          ),
          const SizedBox(height: 16),
          ClipRRect(
            borderRadius: BorderRadius.circular(24),
            child: SizedBox(
              height: 250,
              child: MobileScanner(
                controller: MobileScannerController(
                  detectionSpeed: DetectionSpeed.noDuplicates,
                  returnImage: false,
                ),
                onDetect: (capture) {
                  if (!_scannerEnabled) {
                    return;
                  }
                  final value = capture.barcodes.first.rawValue;
                  if (value == null || value.isEmpty) {
                    return;
                  }
                  _playScanFeedback();
                  setState(() {
                    _barcodeController.text = value;
                    _scannerEnabled = false;
                  });
                  _syncAutoSku();
                  Future<void>.delayed(const Duration(seconds: 2), () {
                    if (mounted) {
                      setState(() {
                        _scannerEnabled = true;
                      });
                    }
                  });
                },
              ),
            ),
          ),
          const SizedBox(height: 16),
          TextField(
            controller: _barcodeController,
            onChanged: (_) => _syncAutoSku(),
            decoration: _scanInputDecoration(
              "Barcode",
              hintText: "เช่น STK000001",
              suffixIcon: _newProductMode
                  ? IconButton(
                      onPressed: _isGeneratingBarcode ? null : _generateBarcode,
                      icon: _isGeneratingBarcode
                          ? const SizedBox(
                              width: 18,
                              height: 18,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : const Icon(Icons.auto_awesome),
                      tooltip: "สร้าง barcode อัตโนมัติ",
                    )
                  : null,
            ),
          ),
          if (_newProductMode) ...[
            const SizedBox(height: 8),
            Align(
              alignment: Alignment.centerLeft,
              child: TextButton.icon(
                onPressed: _isGeneratingBarcode ? null : _generateBarcode,
                icon: const Icon(Icons.qr_code_2_outlined),
                label: const Text("สร้าง barcode สินค้าใหม่อัตโนมัติ"),
              ),
            ),
          ],
          const SizedBox(height: 12),
          if (!_newProductMode) ...[
            SegmentedButton<String>(
              segments: const [
                ButtonSegment(
                    value: "in",
                    label: Text("รับเข้า"),
                    icon: Icon(Icons.call_received)),
                ButtonSegment(
                    value: "out",
                    label: Text("จ่ายออก"),
                    icon: Icon(Icons.call_made)),
                ButtonSegment(
                    value: "issue",
                    label: Text("เบิกใช้"),
                    icon: Icon(Icons.assignment_turned_in_outlined)),
              ],
              selected: {_action},
              onSelectionChanged: (selection) {
                setState(() {
                  _action = selection.first;
                });
              },
            ),
            const SizedBox(height: 12),
          ],
          TextField(
            controller: _qtyController,
            keyboardType: TextInputType.number,
            decoration: _scanInputDecoration(
              "จำนวน",
              hintText: "1",
            ),
          ),
          const SizedBox(height: 12),
          TextField(
            controller: _referenceController,
            decoration: _scanInputDecoration(
              "เลขความปลอดภัย/อ้างอิง",
              hintText: "ถ้ามี",
            ),
          ),
          const SizedBox(height: 12),
          TextField(
            controller: _noteController,
            maxLines: 2,
            decoration: _scanInputDecoration(
              "หมายเหตุ",
              hintText: "รายละเอียดเพิ่ม",
            ),
          ),
          if (_newProductMode) ...[
            const SizedBox(height: 12),
            TextField(
              controller: _productNameController,
              onChanged: (_) => _syncAutoSku(),
              decoration: _scanInputDecoration(
                "ชื่อสินค้า",
                hintText: "เช่น Motor",
              ),
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _productSkuController,
                    onChanged: (value) {
                      final trimmed = value.trim();
                      _isSkuManuallyEdited = trimmed.isNotEmpty &&
                          trimmed != _lastAutoGeneratedSku;
                    },
                    decoration: _scanInputDecoration(
                      "SKU",
                      hintText: "สร้างอัตโนมัติ",
                      suffixIcon: IconButton(
                        onPressed: () =>
                            setState(() => _syncAutoSku(force: true)),
                        icon: const Icon(Icons.auto_awesome_outlined),
                        tooltip: "สร้าง SKU อัตโนมัติ",
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: TextField(
                    controller: _productUnitController,
                    decoration: _scanInputDecoration(
                      "หน่วย",
                      hintText: "pcs",
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 6),
            Text(
              "ปล่อยว่างได้ ระบบจะสร้าง SKU ให้จากชื่อสินค้าและ barcode อัตโนมัติ",
              style: Theme.of(context).textTheme.bodySmall?.copyWith(
                    color: brandInk.withOpacity(0.84),
                    fontWeight: FontWeight.w600,
                  ),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _productCategoryController,
              decoration: _scanInputDecoration(
                "หมวดหมู่",
                hintText: "เช่น ไฟฟ้า",
              ),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _productLocationController,
              decoration: _scanInputDecoration(
                "ตำแหน่งจัดเก็บ",
                hintText: "เช่น Rack A1",
              ),
            ),
          ],
          const SizedBox(height: 16),
          FilledButton.icon(
            onPressed: _isSubmitting ? null : _submit,
            icon: _isSubmitting
                ? const SizedBox(
                    width: 18,
                    height: 18,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  )
                : const Icon(Icons.send),
            label: Text(_newProductMode
                ? "สร้างสินค้าใหม่และรับเข้า"
                : "บันทึกรายการ"),
          ),
          if (_lastResult != null) ...[
            const SizedBox(height: 20),
            _ScanResultCard(
              result: _lastResult!,
              onOpenCode: () => widget.onOpenProductDetails(
                context,
                _lastResult!.product,
              ),
            ),
          ],
        ],
      ),
    );
  }
}

class _ScanResultCard extends StatelessWidget {
  const _ScanResultCard({
    required this.result,
    this.onOpenCode,
  });

  final ScanResult result;
  final VoidCallback? onOpenCode;

  @override
  Widget build(BuildContext context) {
    final tone = result.lowStock ? brandPrimary : brandDeep;
    return Container(
      padding: cardPadding,
      decoration: softPanelDecoration(
        tone: tone,
        surfaceStrength: 0.70,
      ).copyWith(
        border: Border.all(color: tone.withOpacity(0.24)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            result.productCreated
                ? "สร้างสินค้าใหม่และบันทึกรายการสำเร็จ"
                : result.lowStock
                    ? "บันทึกแล้ว: สินค้าอยู่ในระดับเตือน"
                    : "บันทึกสำเร็จ",
            style:
                Theme.of(context).textTheme.titleMedium?.copyWith(color: tone),
          ),
          const SizedBox(height: 8),
          Text(result.product.name),
          Text("บาร์โค้ด: ${result.product.barcode}"),
          Text("คงเหลือ: ${result.product.currentStock} ${result.product.unit}"),
          Text("ผู้ทำรายการ: ${result.movement.actorName}"),
          if (onOpenCode != null) ...[
            const SizedBox(height: 12),
            OutlinedButton.icon(
              onPressed: onOpenCode,
              icon: const Icon(Icons.qr_code_2_outlined),
              label: const Text("ดู barcode / QR"),
            ),
          ],
        ],
      ),
    );
  }
}

class _PageHeader extends StatelessWidget {
  const _PageHeader({
    required this.title,
    required this.subtitle,
    this.showBackButton = false,
  });

  final String title;
  final String subtitle;
  final bool showBackButton;

  @override
  Widget build(BuildContext context) {
    final headerColor = Color.lerp(brandSurfaceStrong, brandPrimary, 0.34)!;
    return Container(
      padding: const EdgeInsets.fromLTRB(spaceLg, spaceLg, spaceLg, spaceMd),
      decoration: BoxDecoration(
        color: headerColor,
        borderRadius: BorderRadius.circular(radiusXl),
        border: Border.all(color: brandPrimary.withOpacity(0.16)),
        boxShadow: [
          BoxShadow(
            color: brandPrimary.withOpacity(0.10),
            blurRadius: 18,
            offset: const Offset(0, 10),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (showBackButton) ...[
            IconButton(
              onPressed: () => Navigator.of(context).maybePop(),
              icon: const Icon(Icons.arrow_back_rounded),
              color: brandDeep,
              style: IconButton.styleFrom(
                backgroundColor: Colors.white.withOpacity(0.82),
              ),
            ),
            const SizedBox(height: spaceXs),
          ],
          Text(
            title,
            style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                  color: brandDeep,
                ),
          ),
          const SizedBox(height: 6),
          Text(
            subtitle,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: brandInk.withOpacity(0.82),
                ),
          ),
          const SizedBox(height: spaceSm),
          Container(
            width: 64,
            height: 4,
            decoration: BoxDecoration(
              color: brandPrimary,
              borderRadius: BorderRadius.circular(999),
            ),
          ),
        ],
      ),
    );
  }
}
